language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t react-app -f Dockerfile.dev .

script:
    - docker run -e CI=true react-app npm run test

deploy:
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "docker-learning"
    env: "DockerLearning-env"
    bucket_name: "elasticbeanstalk-ap-south-1-961871109887"
    bucket_path: "docker-learning"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY